### ISSUE TITLE
Hard-coded ICS example not included

### ISSUE THREAD

**Issue by lsinger** [alt-code/TaskLights#2]
`node main.js` gives:

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './test-data/parnin.ics'
```

Maybe include suitable test data?

**Comment by ssmirr** [comment]
The script that you need to run is `blink.js`.
We were doing some other stuff before which we didn't continue working on and that was in `main.js`. Please disregard that file for now.

**Comment by ssmirr** [comment]
@lsinger I think `README.md` in src directory confused you. I've updated that file with new instructions: https://github.com/alt-code/TaskLights/blob/master/src/README.md

Thank you!
